from translater import flores_codes
from pdfParser import extractRawText
from gptCleaner import getCleanText
from htmlTranslater import translateHTML
import weasyprint
import os

# inp = input("Enter the path to the pdf file: ")
# tgt_lang = input("Enter the language to be translated into: ")
inp = "/mnt/c/Users/Samik Goyal/Documents/test_judgement-1-2.pdf"
tgt_lang = "hin_Deva"

if tgt_lang not in flores_codes:
    raise "Language code not supported"

rawText = extractRawText(inp)
print("Raw text extracted from pdf:")
print(rawText)
print("----------------------------")

cleanText = getCleanText(rawText).strip()
if not cleanText.startswith("```html") or not cleanText.endswith("```"):
    raise "Invalid output by GPT"
cleanText = cleanText[7:-3]
print("Clean text generated by GPT:")
print(cleanText)
print("----------------------------")

translatedText = translateHTML(cleanText, tgt_lang)
print("Translated text:")
print(translatedText)
print("----------------------------")

with open("output.html", "w") as f:
    f.write(translatedText)
print("HTML generated successfully")

weasyprint.HTML(string=translatedText).write_pdf("output.pdf")
print("PDF generated successfully")