from translater import flores_codes
from pdfParser import extractRawText
from gptCleaner import getCleanText
from htmlTranslater import translateHTML
import os

# inp = input("Enter the path to the pdf file: ")
inp = "/mnt/c/Users/Samik Goyal/Documents/test_judgement-1-2.pdf"
rawText = extractRawText(inp)
print("Raw text extracted from pdf:")
print(rawText)
print("----------------------------")
cleanText = getCleanText(rawText)
print("Clean text generated by GPT:")
print(cleanText)
print("----------------------------")
translatedText = translateHTML(cleanText, "hin_Deva")
print("Translated text:")
print(translatedText)
print("----------------------------")